### PR TITLE
refactor: enhance code readability

### PR DESCRIPTION
**Pull request by kychok98**
-remove redundant function call, perform function on useEffect
-rename state

### CODE REVIEW

**Comment by anup-a** [comment]
Great work👍. I was planning to refactor the codebase.

1. Just an issue wave is rendering twice when pressed random button.

**Comment by kychok98** [comment]
> Great work👍. I was planning to refactor the codebase.
> 
> 1. Just an issue wave is rendering twice when pressed random button.
> 2. With some modifications in useEffect, this PR could fix #15

For **1.** I have fixed in the newest commit,
meanwhile, **2** I think it might not able to fix in useEffect, it was due to Wavery class generateSvg, currently not only color will change the wave "design", both layers and heights are being affected.

**Comment by anup-a** [comment]
@kychok98 great I think it is ready to merge.👍
For 2. I think you are right, I will look into that later.

**Comment by anup-a** [comment]
Just noted that default color seems to be changed.

**Pull request merged**
