### PR TITLE
use stopOpacity instead of #RRGGBBAA

### LINKED ISSUE #26: Compatibility issue around CSS style hex color string with opacity (formats like #RRGGBBAA)
Some old and quirky browsers may have issue parsing CSS style hex color written in #RRGGBBAA. They just fallback to initial value, if there is any. And since the fill of these wave paths are transparent by default generated with this awesome tool, users who are using these browsers can only see black waves with no transparency.

TBS cannot handle #RRGGBBAA color properly

Fixing the problem can be rather simple. It is said that CSS style hex color string with opacity (#RRGGBBAA) can only be tolerated by modern browers like Chromium or Firefox (and newer version of Safari, maybe? I really don't know). It's recommended to use regular #RRGGBB or html colors like whitesmoke for attributes like `fill` or `stroke`, and use `fill-opacity` for, you know, fill opacity, and use `stop-opacity` for `<linearGradient>` and `<radialGradient>` like wise. There is also an attribute opacity described [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/opacity), but I won't use that for setting up opacity for background (Or maybe? Why not). All of these "opacity" variants are Number from 0.0 to 1.0. Value that falls out of the range would be clamped to the range.

Well, I was mainly talking about Tencent Browsing Service, a WebView utility developed by a evil mega crop dedicated to Android which is infamous for its compatibility and performance issues, but unfortunately have a relatively huge (I mean, HUGEEEE!!!) user base in China thanks to the mega app, WeChat. Other webkit based browsers may also experience this issue, so it would be nice to fix that.

### PR DESCRIPTION
**Pull request by il3ven**
Closes #26 

Mapped opacity array from 0 to 1
```diff
- export const OPACITY_ARR = ['44', '66', '88', 'ff']
+ export const OPACITY_ARR = ['0.267', '0.4', '0.534', '1']
```

Tested the output with browser stack.

## Earlier
image

## Now
image

### CODE REVIEW

**Comment by anup-a** [comment]
@il3ven There is a bug while changing colors (not gradient), for some reason wave colors turn into black. You can preview it in vercel link - Preview: https://svgwave-git-fork-il3ven-stopopacity-anup-a.vercel.app

image

**Comment by il3ven** [comment]
> @il3ven There is a bug while changing colors (not gradient), for some reason wave colors turn into black. You can preview it in vercel link - Preview: https://svgwave-git-fork-il3ven-stopopacity-anup-a.vercel.app

Yes, there it is. I'll look into it today.

**Comment by il3ven** [comment]
@anup-a Fixed the bug

**Comment by anup-a** [comment]
Sorry, this was really careless from my side. I did not take a look at this project for quite a while.

**Pull request closed without merging**
