### PR TITLE
feat: Added Slider for Wave Height 

### LINKED ISSUE #2: [React] [SVG] Add a slider to adjust different vertical between waves 🌊
As of now there is default height for each layer of waves ( an defined in constants), the task is to add a slider input to manually  change the vertical distance between the waves.

- Fit slider in the customization Bar ( a suggestion to fit it vertically besides other sliders )
- Remove height array from constants and change it dynamically

### PR DESCRIPTION
**Pull request by Remakh**
Resolves #2

### CODE REVIEW

**Comment by anup-a** [comment]
@Remakh Nice work.
Just a thing that there is small clutter while increasing the height. ( blank white space at the bottom ).

Could you try to fix that with transition delay or something else?
It's okay either way.

**Comment by anup-a** [comment]
Another thing....could you remove `package-lock.json ` from your PR.

**Comment by Remakh** [comment]
Yeah sure will do

**Comment by Remakh** [comment]
Couldn't change it with transition delay unfortunately. Only way I got the wave to stick to the bottom was removing transitions all together. Any idea which transition property affects the wave sticking to the bottom? Removed the package-lock file as well

**Comment by anup-a** [comment]
@Remakh no issues I'll take a look into that later.... rest looks good.  You could commit your changes.

**Comment by Remakh** [comment]
Thanks. I think I'm done with the slider. Is there anything else, or do you think we could merge ?

**Comment by anup-a** [comment]
Great work. I think it is ready to merge.
Give us ⭐ on this repo.

**Comment by Remakh** [comment]
Thanks, will do!

**Pull request merged**
